name             'singlenode-hadoop'
maintainer       'Ryan Briones'
maintainer_email 'ryan.briones@brionesandco.com'
license          'BSD'
description      'Installs/Configures singlenode-hadoop'
long_description 'Installs/Configures singlenode-hadoop'
version          '0.1.0'

depends          'java'
depends          'hadoop'